server:
  port: 8081

spring:
  application:
    name: user-service # must match lb://USER-SERVICE in gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
